name: Static analysis

on:
  workflow_dispatch:
#  [pull_request]

jobs:
  pre-commit-checks:
    name: Pre-commit checks on generated project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit cookiecutter
      - name: Generate collection
        run: |
          cookiecutter --no-input --overwrite-if-exists .
      - name: Run pre-commit on generated collection
        run: |
          cd nebulaplugins-collection
          git init
          git config user.email "test@example.com"
          git config user.name "Test"
          git add .
          git commit -m "Test commit"
          pre-commit run --show-diff-on-failure --color=always --all-files
